### ISSUE TITLE
Use non-breaking space between values and their labels

### ISSUE THREAD

**Issue by Kernald** [Vidabe/cooking-units#22]
Currently the separator between a number and its unit seems to be a regular space (I tried to find that in the source, but I'm definitely not familiar with LaTeX enough to figure that one out...). As a result, it's possible to end up with a line-break between them.

I'm not sure about the rules in each language etc, but there's definitely an argument to be made that using a non-breaking space here would make things easier to read. Wikipedia actually has [an entry on that topic in its style guide](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Non-breaking_spaces). I'm curious to hear opinions on the topic.

**Comment by Vidabe** [comment]
(I am going to assume you are using `\cutext` or `\Cutext` while encountering the problem.)

You are right, currently the space between number and unit is a simple `\space` command. I was never quite sure which space is used in which situation so I just used a normal one and stuck with it. I guess because it never bothered me personally I never changed it, but yeah, you are right, it should probably be a non-breakable space. I will fix this in the new version.

Although, if one uses numerals I think a hard space between the numeral and the unit wouldn't be correct. Hmm ... I will think about this.


PS. If you want to use an unbreakable space for `\cutext` and `\Cutext` you can use `\cusetup{cutext-space=~}` in your document.

**Comment by Kernald** [comment]
I was indeed talking about `\cutext` and `\Cutext`, sorry, I could have been more explicit. I think it would make sense to use this for `\cunum` etc as well, though.

Thanks for the `\cusetup` hint! I'll use this in the meantime.

**Comment by Vidabe** [comment]
I've uploaded the newest version to CTAN so an unbreakable space should be the default from now on.
